### PR TITLE
OpenAPI: Fix circular schema

### LINKED ISSUE #979: Still doesn't generate Discord Open API spec
Hello friends :) After trying this last year, figured I'd give it another whirl.  I'm following the getting started guide using the following spec: 

https://github.com/discord/discord-api-spec/blob/main/specs/openapi.json

Now at runtime the page never loads, and I am getting errors like this:

```
ERR RangeError: Maximum call stack size exceeded
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:7:28)
    at <anonymous> (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:33:7)
    at Array.map (<anonymous>)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:32:16)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at <anonymous> (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:33:7)
    at Array.map (<anonymous>)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:32:16)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at <anonymous> (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:33:7)
    at Array.map (<anonymous>)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:32:16)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at <anonymous> (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:33:7)
    at Array.map (<anonymous>)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:32:16)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at <anonymous> (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:33:7)
    at Array.map (<anonymous>)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:32:16)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at <anonymous> (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:33:7)
    at Array.map (<anonymous>)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:32:16)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at <anonymous> (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:33:7)
    at Array.map (<anonymous>)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:32:16)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at <anonymous> (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:33:7)
    at Array.map (<anonymous>)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:32:16)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at <anonymous> (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:33:7)
    at Array.map (<anonymous>)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:32:16)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19)
    at <anonymous> (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:33:7)
    at Array.map (<anonymous>)
    at handleCircularRefs (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:32:16)
    at ii (/Users/justinbeckwith/Code/my-app/node_modules/zudoku/src/lib/oas/graphql/circular.ts:39:19) {
  path: [
    'schema',     'tag',
    'operations', 177,
    'responses',  1,
    'content',    0,
    'schema'
  ],
  locations: [ { line: 90, column: 7 } ],
  extensions: [Object: null prototype] {}
}
```

Previous issue was #181 and got closed.

### PR DESCRIPTION
**Pull request by dan-lee**
This builds on #1002 as this fixes other important issues too.

This should fix #979

### CODE REVIEW

File: packages/zudoku/src/lib/components/context/ZudokuContext.ts [hunk 1]
```diff
@@ -67,8 +67,7 @@ export const useCurrentNavigation = () => {
 
   const { data } = useSuspenseQuery({
     queryFn: () => getPluginSidebar(location.pathname),
-    // We just want to suspend here and don't store in SSR dehydrated state
-    queryKey: ["plugin-sidebar", NO_DEHYDRATE, location.pathname],
+    queryKey: ["plugin-sidebar", location.pathname],
```
Comment (dan-lee) [inline packages/zudoku/src/lib/components/context/ZudokuContext.ts:70]: Unfortunately this triggered suspense boundaries to trigger after page reload. This will increase the size of the built static file but at least won't trigger a jumping page

**Review by mosch — APPROVED** [review]
