### PR TITLE
Close Websocket on Vite server restart

### LINKED ISSUE #714: "server.handleUpgrade() was called more than once..." error on hot reload
My server is running fine, but when I make a change to zudoku.config.ts it hangs with the following:

```
[1] Uncaught exception Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration
[1]     at WebSocketServer.completeUpgrade (../docs/node_modules/vite/dist/node/chunks/dep-M1IYMR16.js:37496:13)
[1]     at WebSocketServer.handleUpgrade (.../docs/node_modules/vite/dist/node/chunks/dep-M1IYMR16.js:37473:10)
[1]     at handleUpgrade (.../docs/node_modules/vite/dist/node/chunks/dep-M1IYMR16.js:37853:9)
[1]     at Server.hmrServerWsListener (.../docs/node_modules/vite/dist/node/chunks/dep-M1IYMR16.js:37876:9)
[1]     at Server.emit (node:events:525:35)
[1]     at onParserExecuteCommon (node:_http_server:950:14)
[1]     at onParserExecute (node:_http_server:852:3)
[1]     at HTTPParser.callbackTrampoline (node:internal/async_hooks:130:17)
[1] npm run docs:dev exited with code 0
```

My config is pretty normal:

```
import type { ZudokuConfig } from "zudoku";

const config: ZudokuConfig = {
  page: {
    pageTitle: "API Guide",
    logo: {
      src: {
        light: "/logos/logo-wide-transparent.png",
        dark: "/logos/logo-wide-transparent-darmmode.png"
      },
      width: "120px"  // Adjust this value based on the actual logo size
    }
  },
  topNavigation: [
    { id: "docs", label: "Documentation" },
    { id: "api", label: "API Reference" },
  ],
  sidebar: {
    docs: [
      {
        type: "category",
        label: "Overview",
        items: ["introduction", "example"],
      },
    ],
  },
  redirects: [{ from: "/", to: "/docs/introduction" }],
  apis: {
    type: "file",
    input: "./apis/openapi.yaml",
    navigationId: "api"
  },
  docs: {
    files: "/pages/**/*.{md,mdx}",
  },
};

export default config;

```

Not sure if I did something wrong?

### PR DESCRIPTION
**Pull request by dan-lee**
should fix #714

### CODE REVIEW

File: packages/zudoku/src/vite/plugin-config-reload.ts [hunk 1]
```diff
@@ -26,6 +26,7 @@ export const createConfigReloadPlugin = (
         // Assume `.tsx` files are handled by HMR (skip if the config file itself changed)
         if (file !== newConfig.__meta.path && file.endsWith(".tsx")) return;
 
+        await ws.close();
```
Comment (dan-lee) [inline packages/zudoku/src/vite/plugin-config-reload.ts:29]: This is the main fix

**Review by mosch — APPROVED** [review]
