### PR TITLE
fix: "Open Markdown page" redirects to correct URL when path differs from filename

### LINKED ISSUE #2269: "Open Markdown page" redirects to wrong URL when path differs from filename
For a page that has a URL different to a filename, e.g. going to `/` with the following Zudoku config:

```js
{
  navigation: [
    {
      items: [
        {
          type: "doc",
          file: "my-file",
          path: "/"
        },
        // ...
      ]
    }
  ],
  // ...
}
```

clicking the "Copy page -> Open Markdown page" button routes to `/.md` instead of the correct `/my-file.md` (or maybe the md file should be generated based on the path instead of the filename?). This causes a 404 in this case.

### PR DESCRIPTION
**Pull request by mosch**
## Summary

When a doc has a custom path of "/" (e.g. `file: "my-file"`, `path: "/"`), the "Open Markdown page" button generated `/.md` which causes a 404.

- MdxPage now maps root pathname `/` to `/index.md` (consistent with how `getMarkdownOutputPath` writes root routes as `index.md` in production)
- The dev middleware reverses this mapping (`/index` → `/`) so it can look up the correct file
- Adds 14 regression tests covering `getMarkdownOutputPath`, `getMarkdownPathname`, `resolveMarkdownRoutePath`, and roundtrip consistency

Fixes #2269

## Test plan

- [x] `pnpm vitest run packages/zudoku/src/vite/plugin-markdown-export.test.ts` — 14 tests pass
- [x] `pnpm -F zudoku typecheck` — clean
- [x] `pnpm biome ci` — clean
- [ ] CI Build & Test

https://claude.ai/code/session_01HPTu9jq9XW8JELsq3wmx8V

### CODE REVIEW

File: packages/zudoku/src/vite/plugin-markdown-export.ts [hunk 1]
```diff
@@ -55,6 +55,23 @@ export const getMarkdownOutputPath = (distDir: string, routePath: string) => {
...
+ */
+export const resolveMarkdownRoutePath = (
+  requestUrl: string,
+  basePath: string,
+): string => {
+  const pathname = requestUrl.split(/[?#]/)[0] ?? requestUrl;
+  let routePath = joinUrl(
+    pathname.slice(basePath.length).replace(/\.mdx?$/, ""),
+  );
+  if (routePath === "/index") routePath = "/";
```
Comment (mosch) [inline packages/zudoku/src/vite/plugin-markdown-export.ts]:
```suggestion
  if (routePath === "/index") {
    return "/";
  }
```

File: packages/zudoku/src/vite/plugin-markdown-export.ts [hunk 2]
```diff
@@ -55,6 +55,23 @@ export const getMarkdownOutputPath = (distDir: string, routePath: string) => {
...
+ * Resolves a .md request URL to the route path used in the file mapping.
+ * Strips query/hash, removes the .md(x) extension, and reverses the
+ * "/index" → "/" mapping from getMarkdownPathname.
+ */
+export const resolveMarkdownRoutePath = (
+  requestUrl: string,
+  basePath: string,
+): string => {
+  const pathname = requestUrl.split(/[?#]/)[0] ?? requestUrl;
+  let routePath = joinUrl(
```
Comment (mosch) [inline packages/zudoku/src/vite/plugin-markdown-export.ts]:
```suggestion
  const routePath = joinUrl(
```

**Review by dan-lee — APPROVED** [review]
